@startuml

interface "user input (Moscow)" as user1
interface "user input (Novosibirsk)" as user2

component "CDN (Moscow)" as cdn1
component "CDN (Novosibirsk)" as cdn2

component "API Gateway" as gateway

component "Service Discovery (Consul)" as consul

package "pymongo-api" {
    [api1]
    [api2]
    [api3]
}

database "MongoDB" {
    [router]
    [configSrv]

    frame "Shards" {
        frame "Shard 1 replica set" {
            [shard1_primary]
            [shard1_secondary1]
            [shard1_secondary2]
        }
        frame "Shard 2 replica set" {
            [shard2_primary]
            [shard2_secondary1]
            [shard2_secondary2]
        }
        frame "Shard 3 replica set" {
            [shard3_primary]
            [shard3_secondary1]
            [shard3_secondary2]
        }
    }
}

user1 --> cdn1
user2 --> cdn2

user1 --> gateway
user2 --> gateway

gateway -up-> consul
[pymongo-api] -up-> consul
gateway --> [pymongo-api]

[pymongo-api] -down-> router
router --> configSrv
router --> [Shards]

shard1_primary --> shard1_secondary1
shard1_primary --> shard1_secondary2

shard2_primary --> shard2_secondary1
shard2_primary --> shard2_secondary2

shard3_primary --> shard3_secondary1
shard3_primary --> shard3_secondary2

[Shards] --> configSrv

[pymongo-api] -right-> [redis]


@enduml